export class HistoriqueCaisse {
    IDECRITURE!:number
    LibelleEcriture!:string
    NumeroMouvement!:number
    CodeCompte!:string
    MontantDebit!:string
    MontantCredit!:string
    IDPRODUIT!:number
    Validee!:boolean
    DateHeure!:string
    IDEleveOuEns!:number
    bAnalytique!:boolean
    bCumul!:boolean
    MontantAvance!:string
    NumAvance!:number
    IDCAISSE!:number
    TauxTVA!:string
    MontantTVA!:string
}